name: Build Magic 8Ball
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  publish:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Github Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag magic-8ball:latest
      - name: Tag the Docker image
        run: docker tag magic-8ball:latest docker.pkg.github.com/berryscottr/magic-8ball/magic-8ball:latest
      - name: Push the Docker image
        run: docker push docker.pkg.github.com/berryscottr/magic-8ball/magic-8ball:latest
      - name: Run the Docker image
        run: docker run docker.pkg.github.com/berryscottr/magic-8ball/magic-8ball:latest
