name: Build Magic 8Ball
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  publish:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag magic-8ball
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Upload the Docker image
        run: docker push magic-8ball
      - name: Run the Docker image
        run: docker run magic-8ball
#  run:
#    runs-on: ubuntu-latest
#    services:
#      magic-ball:
#        image: magic-8ball
#        ports:
#          - "8080:8080"
#    steps:
#      - uses: actions/checkout@v3
#      - name: Run the Docker image
#        run: docker run --rm -p 8080:8080 magic-8ball