name: updateSkills

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          pip install matplotlib openpyxl pandas seaborn
      - name: execute py script
        working-directory: ./scripts
        run: |
          python slmatchups.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: berryscottr
          author_email: berryscottr@gmail.com
          message: 'Automated commit of skill updates'
          add: '.'
      - name: Push changes
        run: |
          git push