name: updateSkills

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: execute py script
        run: |
          python ./scripts/slmatchups.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: berryscottr
          author_email: berryscottr@gmail.com
          message: 'Automated commit of skill updates'
          add: '.'
      - name: Push changes
        run: |
          git push